inline:
  - '-on'
  - '-off'
balance:
  - '-on'
  - '-off'
style:
  - stp
  - flp
  - frp
factor:
  - 0
  - 2
state:
  - '-on'
  - '-off'
arrtype:
  - block
  - cyclic
opimpl:
  int:
    - fabric
    - dsp
  float:
    - fabric
    - fulldsp
    - primitivedsp
  double:
    - fabric
    - fulldsp
  half:
    - fabric
    - fulldsp
sttype:
  - ram_1p
  - ram_1wnr
  - ram_2p
  - ram_s2p
stimpl:
  - bram
stltc:
  - -1
opltc:
  - -1
POW:
  - 0.412
CLK:
  - 6.524
LATENCY:
  - 842
LUT:
  - 10321
FF:
  - 11834
DSP:
  - 12
BRAM:
  - 6
URAM:
  - 0
SRL:
  - 2715

