top:
    - ms_mergesort
funcList:
    - merge
loopList:
    group1:
        level:
            - ms_mergesort/mergesort_label1
        unroll:
            - ms_mergesort/mergesort_label1
        pipeline:
            - ms_mergesort/mergesort_label1
        flatten:
            -
    group2:
        level:
            - ms_mergesort/mergesort_label2
        unroll:
            - ms_mergesort/mergesort_label2
        pipeline:
            - ms_mergesort/mergesort_label2
        flatten:
            -
    group3:
        level:
            - merge/merge_label1
            - merge/merge_label2
            - merge/merge_label3
        unroll:
            - merge/merge_label1
            - merge/merge_label2
            - merge/merge_label3
        pipeline:
            - merge/merge_label1
            - merge/merge_label2
            - merge/merge_label3
        flatten:
            -
arrList:
    - ms_mergesort a
    - merge temp
interList:
    - 
dictOp:
    int:
        ms_mergesort/mergesort_label1 i:
            - add
        ms_mergesort/mergesort_label2 i:
            - add
        ms_mergesort/mergesort_label2 m:
            - add
        merge/merge_label1 i:
            - add
        merge/merge_label2 j:
            - add
        merge/merge_label3 k:
            - add
    float:
        -
    double:
        -
    half:
        -

